name: your_drive
description: A high-performance Drive-like app powered by Telegram MTProto.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ Networking
  dio: ^5.4.0
  http: ^1.2.0

  # ðŸ”¹ File picker
  file_picker: ^10.3.10

  # ðŸ”¹ File system
  path_provider: ^2.1.2
  path: ^1.9.0

  # ðŸ”¹ Media / UI helpers
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  chewie: ^1.13.0
  video_player_win: ^3.2.2

  # ðŸ”¹ Supabase
  supabase_flutter: ^2.12.0

  # ðŸ”¹ Gallery & Permissions
  device_info_plus: ^10.1.0
  photo_manager: ^3.0.0
  permission_handler: ^12.0.1

  # ðŸ”¹ Local State & Background
  shared_preferences: ^2.2.0
  connectivity_plus: ^7.0.0
  battery_plus: ^7.0.0
  workmanager: ^0.9.0+3
  google_sign_in: ^6.2.1
  photo_view: ^0.15.0
  local_auth: ^2.3.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  timeago: ^3.6.1
  flutter_foreground_task: ^8.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  share_plus: ^7.0.0
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  cryptography: ^2.7.0
  flutter_pdfview: ^1.3.2
  open_filex: ^4.3.4
  flutter_local_notifications: ^17.0.0
  flutter_background_service: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  remove_alpha_ios: true