name: your_drive
description: Drive-like Flutter app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ Networking (Telegram bot / backend)
  http: ^1.2.0

  # ðŸ”¹ File picker
  file_picker: ^10.3.10

  # ðŸ”¹ File system (DOWNLOAD SUPPORT âœ… REQUIRED)
  path_provider: ^2.1.2

  # ðŸ”¹ Media / UI helpers
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  chewie: ^1.13.0
  video_player_win: ^3.2.2

  # ðŸ”¹ Supabase (Auth + Database)
  supabase_flutter: ^2.12.0

  photo_manager: ^3.0.0  # To access Gallery
  permission_handler: ^12.0.1 # For permissions
  shared_preferences: ^2.2.0 # To remember which files we already uploaded

  connectivity_plus: ^7.0.0  # To check for Wi-Fi
  battery_plus: ^7.0.0       # To check if charging
  workmanager: ^0.9.0+3
  google_sign_in: ^6.2.1

flutter:
  uses-material-design: true
